## Author : Akula Venkata Satya Sai Gopinadh
## RegNo: 22228 
## Date : 10-07-2023

In [1]:
import numpy as np
import torch

Tensors can be initialized in various ways. Take a look at the following examples:

### Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [2]:
data = [[1,2], [3,4]]

x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

### From a NumPy array



In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

### From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [4]:
x_ones = torch.ones_like(x_data)
print(f" Ones tensor : \n {x_ones} ")


 Ones tensor : 
 tensor([[1, 1],
        [1, 1]]) 


In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f" Random tensor : \n {x_rand}")

 Random tensor : 
 tensor([[0.1806, 0.4477],
        [0.5799, 0.5138]])


### With random or constant values:

Shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
print(f"Random Tensor: \n {rand_tensor} \n")

Random Tensor: 
 tensor([[0.3288, 0.2961, 0.1736],
        [0.8201, 0.2170, 0.4260]]) 



In [7]:
ones_tensor = torch.ones(shape)
print(f"Ones Tensor: \n {ones_tensor} \n")

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [8]:
zeros_tensor = torch.zeros(shape)
print(f"Zeros Tensor: \n {zeros_tensor}")

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.


In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")

Shape of tensor: torch.Size([3, 4])


In [10]:
print(f"Datatype of tensor: {tensor.dtype}")

Datatype of tensor: torch.float32


In [11]:
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [12]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

### Standard numpy-like indexing and slicing:

In [23]:
tensor = torch.ones(4, 4) #Matrix of order 4*4

In [17]:
print(f"First row: {tensor[0]}") # taking First row using indexing

First row: tensor([1., 1., 1., 1.])


In [18]:
print(f"First column: {tensor[:, 0]}") # Taking first column using slicing.

First column: tensor([1., 1., 1., 1.])


In [19]:
print(f"Last column: {tensor[..., -1]}") #getting last-column of the 4*4matrix.

Last column: tensor([1., 1., 1., 1.])


In [20]:
tensor[:,1] = 0 
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) #Joining tensors You can use torch.cat
#to concatenate a sequence of tensors along a given dimension
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### Arithmetic Operations

In [38]:
# Matrix Multiplication.
#y1, y2, y3 will have the same value
y1 = tensor @ tensor.T # tensor.T gives the Transpose of the tensor.
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)

torch.matmul(tensor, tensor.T, out=y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [36]:
#his computes the element-wise product.
#z1, z2, z3 will have the same value

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)

torch.mul(tensor, tensor , out=z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### *Single-element tensors* if we have a one-element tensor.


In [40]:
"""Like Aggregating all values of a tensor into one value
and can convert it into a Python numerical value using Item()."""
agg = tensor.sum()
agg_item = agg.item()
print(agg_item)
print(type(agg_item))

16.0
<class 'float'>


### Inplace Operations

In [46]:
print(f"{tensor}\n")

tensor([[17., 17., 17., 17.],
        [17., 17., 17., 17.],
        [17., 17., 17., 17.],
        [17., 17., 17., 17.]])



In [47]:
tensor.add_(4) # _ is the inplace operator.
print(tensor)

tensor([[21., 21., 21., 21.],
        [21., 21., 21., 21.],
        [21., 21., 21., 21.],
        [21., 21., 21., 21.]])


### Tensor --> NumPy array

In [48]:
t = torch.ones(3)
print(f"t : {t}")

t : tensor([1., 1., 1.])


In [49]:
n = t.numpy()
print(f"n : {n}")

n : [1. 1. 1.]


In [51]:
#A change in the tensor reflects in the NumPy array.

t.add_(1)

print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2.])
n : [2. 2. 2.]


### NumPy array --> Tensor

In [61]:
n = np.ones(5) # Using ones array
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [62]:
#A change in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)

print(f"t : {t}")
print(f"n : {n}")


t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]


In [70]:
n = np.random.rand(3) # taking random array

t = torch.from_numpy(n)
t

tensor([0.3368, 0.4274, 0.4783], dtype=torch.float64)

In [71]:
np.subtract(n, 0.125, out =n)

print(f" t : {t}")
print(f" n : {n}")

 t : tensor([0.2118, 0.3024, 0.3533], dtype=torch.float64)
 n : [0.21180627 0.30241057 0.35333763]
